import { Box, CheckCircle2, Clock3, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Modal } from '../components/ui/Modal'
import { PageHeader } from '../components/ui/PageHeader'
import { useLocalStorage } from '../hooks/useLocalStorage'

type Namespace={name:string;team:string;environment:string;cpu:string;memory:string;status:string;created:string}
const initial:Namespace[]=[{name:'commerce-prod',team:'Commerce',environment:'Produção',cpu:'8 vCPU',memory:'16 GiB',status:'Ativo',created:'12/04/2026'},{name:'data-sandbox',team:'Data Platform',environment:'Sandbox',cpu:'4 vCPU',memory:'8 GiB',status:'Ativo',created:'21/05/2026'},{name:'growth-preview',team:'Growth',environment:'Preview',cpu:'2 vCPU',memory:'4 GiB',status:'Provisionando',created:'Agora'}]
export default function NamespacesPage(){
 const [items,setItems]=useLocalStorage<Namespace[]>('opsphere-namespaces',initial),[modal,setModal]=useState(false)
 const [form,setForm]=useState({name:'',team:'',environment:'Desenvolvimento',size:'Pequeno'})
 const create=()=>{if(!form.name||!form.team)return;const sizes:Record<string,[string,string]>={Pequeno:['2 vCPU','4 GiB'],Médio:['4 vCPU','8 GiB'],Grande:['8 vCPU','16 GiB']};setItems(v=>[...v,{name:form.name,team:form.team,environment:form.environment,cpu:sizes[form.size][0],memory:sizes[form.size][1],status:'Provisionando',created:'Agora'}]);setModal(false);setTimeout(()=>setItems(v=>v.map(i=>i.name===form.name?{...i,status:'Ativo'}:i)),2200)}
 return <><PageHeader eyebrow="PLATAFORMA SELF-SERVICE" title="Namespaces Kubernetes" description="Crie ambientes padronizados com limites, políticas e observabilidade." actions={<button className="button button--primary" onClick={()=>setModal(true)}><Plus size={16}/> Solicitar namespace</button>}/>
 <div className="notice-banner"><CheckCircle2/><div><strong>Provisionamento automatizado</strong><span>Todos os namespaces incluem NetworkPolicy, ResourceQuota, RBAC e coleta de logs.</span></div></div>
 <section className="namespace-grid">{items.map(item=><article className="panel namespace-card" key={item.name}><header><div className="resource-icon"><Box/></div><div><h2>{item.name}</h2><span>{item.team}</span></div><button className="icon-button" onClick={()=>setItems(v=>v.filter(i=>i.name!==item.name))}><Trash2 size={16}/></button></header><div className={`provision-status ${item.status==='Ativo'?'is-active':''}`}>{item.status==='Ativo'?<CheckCircle2/>:<Clock3 className="spin"/>}{item.status}</div><dl><div><dt>Ambiente</dt><dd>{item.environment}</dd></div><div><dt>CPU</dt><dd>{item.cpu}</dd></div><div><dt>Memória</dt><dd>{item.memory}</dd></div><div><dt>Criado</dt><dd>{item.created}</dd></div></dl><button className="button button--full">Abrir detalhes</button></article>)}</section>
 {modal&&<Modal title="Solicitar namespace" onClose={()=>setModal(false)}><div className="form-grid"><label>Nome<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})} placeholder="ex.: team-environment"/></label><label>Equipe<input value={form.team} onChange={e=>setForm({...form,team:e.target.value})} placeholder="Equipe responsável"/></label><label>Ambiente<select value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}><option>Desenvolvimento</option><option>Sandbox</option><option>Produção</option></select></label><label>Tamanho<select value={form.size} onChange={e=>setForm({...form,size:e.target.value})}><option>Pequeno</option><option>Médio</option><option>Grande</option></select></label><div className="cost-preview span-2"><span>Custo mensal estimado</span><strong>{form.size==='Grande'?'R$ 1.840':form.size==='Médio'?'R$ 920':'R$ 460'}</strong></div><div className="form-actions span-2"><button className="button" onClick={()=>setModal(false)}>Cancelar</button><button className="button button--primary" onClick={create}>Provisionar</button></div></div></Modal>}</>
}
