import { BookOpen, Check, ChevronRight, Clock3, History, PlayCircle, Plus, RotateCcw } from 'lucide-react'
import { useState } from 'react'
import { Badge } from '../components/ui/Badge'
import { PageHeader } from '../components/ui/PageHeader'
import { useLocalStorage } from '../hooks/useLocalStorage'

const runbooks=[{id:'rb1',title:'Failover do PostgreSQL primário',category:'Banco de dados',steps:['Confirmar indisponibilidade do primary','Verificar lag das réplicas','Promover réplica mais atual','Atualizar endpoint no secrets manager','Validar queries e latência','Registrar timeline do incidente'],duration:'12 min',runs:18},{id:'rb2',title:'Mitigação de latência no checkout',category:'Incidente',steps:['Validar métricas RED','Identificar dependência degradada','Ativar circuit breaker','Escalar réplicas do checkout','Validar taxa de erros'],duration:'8 min',runs:31},{id:'rb3',title:'Rotação de credenciais de produção',category:'Segurança',steps:['Gerar novas credenciais','Atualizar secrets manager','Reiniciar workloads gradualmente','Revogar credenciais anteriores','Validar auditoria'],duration:'20 min',runs:9}]
export default function RunbooksPage(){
 const [selected,setSelected]=useState(runbooks[0]),[completed,setCompleted]=useLocalStorage<Record<string,number[]>>('opsphere-runbooks',{}),[history,setHistory]=useState<string[]>([])
 const checks=completed[selected.id]||[],toggle=(i:number)=>setCompleted(v=>({...v,[selected.id]:checks.includes(i)?checks.filter(x=>x!==i):[...checks,i]}))
 const finish=()=>{setHistory(h=>[`${selected.title} · concluído agora`,...h]);setCompleted(v=>({...v,[selected.id]:[]}))}
 return <><PageHeader eyebrow="CONHECIMENTO OPERACIONAL" title="Runbooks interativos" description="Execute procedimentos confiáveis com checklist e trilha de auditoria." actions={<button className="button"><Plus size={16}/> Novo runbook</button>}/>
 <section className="runbook-layout"><aside className="panel runbook-list"><div className="panel__header"><div><span className="eyebrow">BIBLIOTECA</span><h2>Procedimentos</h2></div><BookOpen size={18}/></div>{runbooks.map(rb=><button className={selected.id===rb.id?'is-selected':''} key={rb.id} onClick={()=>setSelected(rb)}><span className="resource-icon"><PlayCircle/></span><span className="grow"><strong>{rb.title}</strong><small>{rb.category} · {rb.steps.length} passos</small></span><ChevronRight/></button>)}</aside>
 <article className="panel runbook-player"><header><div><Badge tone="info">{selected.category}</Badge><h2>{selected.title}</h2><p><Clock3 size={14}/> {selected.duration} estimados · executado {selected.runs} vezes</p></div><button className="icon-button" onClick={()=>setCompleted(v=>({...v,[selected.id]:[]}))}><RotateCcw size={17}/></button></header><div className="progress-header"><span>Progresso</span><strong>{checks.length} de {selected.steps.length}</strong></div><div className="progress-track"><i style={{width:`${checks.length/selected.steps.length*100}%`}}/></div><div className="checklist">{selected.steps.map((step,i)=><label className={checks.includes(i)?'is-done':''} key={step}><input type="checkbox" checked={checks.includes(i)} onChange={()=>toggle(i)}/><span><Check/></span><div><small>PASSO {i+1}</small><strong>{step}</strong></div></label>)}</div><button disabled={checks.length!==selected.steps.length} className="button button--primary button--full" onClick={finish}>Concluir execução</button></article>
 <aside className="panel history-panel"><div className="panel__header"><div><span className="eyebrow">HISTÓRICO</span><h2>Execuções</h2></div><History size={18}/></div>{history.length?history.map((item,i)=><div className="history-item" key={i}><Check/><span>{item}</span></div>):<div className="empty-compact"><Clock3/><span>Novas execuções aparecerão aqui.</span></div>}</aside></section></>
}
